disqus: ## Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b
gitment:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner: ## Your GitHub ID, e.g. username
  repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. imsun.github.io
  client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
gitalk:
  enable: true ## If you want to use Gitment comment system please set the value to true.
  owner:  MikeoPerfect ## Your GitHub ID, e.g. username
  repo:  MikeoPerfect.github.io ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id: clientId ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: clientSecret ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin:  MikeoPerfect ## Github repo owner and collaborators, only these guys can initialize github issues.
valine: ## https://valine.js.org
  enable: false ## If you want to use Valine comment system, please set the value to true.
  appid: ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appkey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-评论系统中的邮件提醒设置
  verify: false ## Validation code.
  placeholder: Just so so ## Comment box placeholders.
  avatar: 'mm' ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.

google_search: false ## Use Google search, true/false.
baidu_search: false ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
fancybox: false ## If you want to use fancybox please set the value to true.
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: true ## If you want to add list number to toc please set the value to true.
shareto: false ## If you want to use the share button please set the value to true, and you must have hexo-helper-qrcode installed.
busuanzi: false ## If you want to use Busuanzi page views please set the value to true.
wordcount: false ## If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
canvas_nest:
  enable: false ## If you want to use dynamic background please set the value to true, you can also fill the following parameters to customize the dynamic effect, or just leave them blank to keep the default effect.
  color: "100,99,98" ## RGB value of the color, e.g. "100,99,98"
  opacity: "0.7" ## Transparency of lines, e.g. "0.7"
  zIndex: "-1"  ## The z-index property of the background, e.g. "-1"
  count: "150" ## Quantity of lines, e.g. "150"
donate:
  enable: false ## If you want to display the donate button after each post, please set the value to true and fill the following items on your need. You can also enable donate button in a page by adding a "donate: true" item to the front-matter.
  github: ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
  alipay_qr: ## Path of Alipay QRcode image, e.g. /img/AliPayQR.png
  wechat_qr: ## Path of Wechat QRcode image, e.g. /img/WeChatQR.png
  btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
  btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
  paypal_url: ## Paypal URL, e.g. https://www.paypal.me/tufu9441
post_copyright:
  enable: true ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: MikeoPerfect ## Your author name, e.g. tufu9441
  copyright_text: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">知识共享署名 4.0 国际许可协议</a> ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: history
    directory: history/
    icon: fa-history
  - page: about
    directory: about/
    icon: fa-book
  - page: 项目
    directory: project/
    icon: fa-star
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - toc
  - search
  - category
  - recent_posts
  - recent_comments
  - links

links:
  - title: MikeoPerfect'd 站点
    url: http://www.mikeoperfect.com
  - title: 王林钊的博客
    url: https://gerlegend.cn/

timeline:
  - num: 1
    word: long long ago
  - num: 2
    word: 2015/09/01-合肥工业大学/物联网工程15-02班
  - num: 3
    word: 2018/07/13~2018/09/30-苏州微软o365 AntiSpam SDE Intern
  - num: 4
    word: 2018/12/02~2019/01/23-有赞零售部Java开发实习生
  - num: 5
    word: 2019/06/15-合肥工业大学/2019届本科毕业
  - num: 6
    word: 2019/06/29-深圳腾讯科技有限公司/PCG研发部/测试开发工程师

# Static files
js: js
css: css

# Theme version
version: 0.0.0
